### ISSUE TITLE
How to handle New Password challenge?

### ISSUE THREAD

**Issue by pbaker5** [jonsaw/amazon-cognito-identity-dart#34]
Hi,

The Use Case 4 says that when Authenticating and a CognitoUserNewPasswordRequiredException is thrown, handle the new password challenge. Looking through cognito_user.dart I can't see a way of doing that. Am I missing something?

Thanks.

**Comment by demsey2** [comment]
@pbaker5 did you find any solution for that, I have the same issue

**Comment by pbaker5** [comment]
> @pbaker5 did you find any solution for that, I have the same issue

Nope.

**Comment by ncb000gt** [comment]
I have a pr up for this flow. You can pull down my changes and try them out: https://github.com/jonsaw/amazon-cognito-identity-dart/pull/22

Note that I'm not sure @jonsaw has had a chance to review the changes yet. But, they worked for me in my very localized testing. Let me know if you run into any issues. :)

**Comment by demsey2** [comment]
thanks for the info, I tried to reference your fork in my pubspec.yaml with the following:
```
amazon_cognito_identity_dart:
    git:
      url: https://github.com/ncb000gt/amazon-cognito-identity-dart.git
      ref: master
```
but this still gets the original package, do you know how to fix that or what is there a better way to handle that?
